openapi: 3.0.3
info:
  title: WASAPhoto API
  description: API for WASAPhoto project
  version: "5"

tags:
  - name: login
    description: Operations related to user login
  - name: user
    description: Operations related to user management
  - name: photos
    description: Operations related to photos

paths:
  /login:
    post:
      tags:
        - login
      summary: Logs in the user
      operationId: doLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 16
              required:
                - name
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string

  /setMyUserName:
    post:
      tags:
        - user
      summary: Set user's username
      operationId: setMyUserName
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: User's username updated successfully

  /uploadPhoto:
    post:
      tags:
        - photos
      summary: Upload a photo
      operationId: uploadPhoto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                caption:
                  type: string
              required:
                - file
      responses:
        '201':
          description: Photo uploaded successfully

  /followUser:
    post:
      tags:
        - user
      summary: Follow a user
      operationId: followUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: User followed successfully

  /unfollowUser:
    post:
      tags:
        - user
      summary: Unfollow a user
      operationId: unfollowUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: User unfollowed successfully

  /banUser:
    post:
      tags:
        - user
      summary: Ban a user
      operationId: banUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: User banned successfully

  /unbanUser:
    post:
      tags:
        - user
      summary: Unban a user
      operationId: unbanUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: User unbanned successfully

  /getUserProfile:
    get:
      tags:
        - user
      summary: Get user profile
      operationId: getUserProfile
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile retrieved successfully

  /getMyStream:
    get:
      tags:
        - photos
      summary: Get user's photo stream
      operationId: getMyStream
      responses:
        '200':
          description: User's photo stream retrieved successfully

  /likePhoto:
    post:
      tags:
        - photos
      summary: Like a photo
      operationId: likePhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
              required:
                - photoId
      responses:
        '201':
          description: Photo liked successfully

  /unlikePhoto:
    post:
      tags:
        - photos
      summary: Unlike a photo
      operationId: unlikePhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
              required:
                - photoId
      responses:
        '200':
          description: Photo unliked successfully

  /commentPhoto:
    post:
      tags:
        - photos
      summary: Comment on a photo
      operationId: commentPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                comment:
                  type: string
              required:
                - photoId
                - comment
      responses:
        '201':
          description: Comment added to the photo

  /uncommentPhoto:
    post:
      tags:
        - photos
      summary: Remove a comment from a photo
      operationId: uncommentPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                commentId:
                  type: string
              required:
                - photoId
                - commentId
      responses:
        '200':
          description: Comment removed from the photo

  /deletePhoto:
    post:
      tags:
        - photos
      summary: Delete a photo
      operationId: deletePhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
              required:
                - photoId
      responses:
        '200':
          description: Photo deleted successfully
